version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    env_file: .env

  # db:
  #   image: postgres:12-alpine
  #   ports:
  #     - "5431:5431"
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=12345678

# volumes:
#   postgres-data: