version: "3"

services:
  app:
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - "5431:5431"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - postgres-data:/var/lib/postgresql/data

  celeryworker:
    depends_on:
      - db
